### ISSUE TITLE
Feature Request: Desktop App for Robotics Academy

### ISSUE THREAD

**Issue by Apoorvgarg-creator** [JdeRobot/RoboticsAcademy-Desktop#10]
**Is your feature request related to a problem? Please describe.**
The current command-line interface (CLI) for accessing Robotics Academy creates a barrier to entry for users who are less familiar with technical commands. To make the Academy more accessible and user-friendly, a desktop application is necessary to provide a graphical user interface (GUI) for easier navigation and interaction.

**Describe the solution you'd like**
We propose the development of a robust desktop application for Robotics Academy that operates seamlessly across Windows, Mac, and Linux operating systems. This application should offer an intuitive and visually appealing interface that allows users to access all features and resources of the Academy without the need for complex CLI commands. Key features of this desktop app should include:

User-friendly Interface: A clean and intuitive interface that enables users to easily navigate through different sections of the Robotics Academy, such as courses, projects, forums, and resources.

Course Management: The ability for users to enroll in courses, track their progress, and access course materials directly from the desktop application.

Project Workspace: Integration of a project workspace where users can create, edit, and collaborate on robotics projects using built-in tools and simulators.

Community Interaction: Seamless integration with the Robotics Academy community forums, allowing users to ask questions, share insights, and engage with other learners directly from the app.

Offline Access: Capability to access certain Academy resources and course materials offline, enabling users to continue learning even without an internet connection.

**Describe alternatives you've considered**
While the current CLI provides access to Robotics Academy, it requires users to have a certain level of technical expertise and familiarity with command-line operations. Developing a desktop application eliminates this barrier by providing a GUI that caters to users of all skill levels, thereby enhancing the accessibility and usability of the Academy.

**Additional context**
By developing a desktop application for Robotics Academy, we aim to democratize access to robotics education and empower learners from diverse backgrounds to explore and engage with robotics concepts in a user-friendly environment. This feature request aligns with our commitment to fostering inclusivity and accessibility within the robotics community.

**Comment by codezerro** [comment]
Hi, I would like to work on thoes features. Could you please assign it to me?

**Comment by jmplaza** [comment]
No, assignment is required at all. Just work on it and submit your PR when ready :-)

**Comment by Apoorvgarg-creator** [comment]
@codezerro Please go ahead and work on this issue. In case of any help please use the github issue forum to discuss.

**Comment by codezerro** [comment]
Hello, @jmplaza and @Apoorvgarg-creator , 
After reviewing the current desktop app codes, I understood that it's redirecting or browsing to the RADI (respect to those who work on this project). 

My proposal is to integrate all the features into the desktop app instead of browsering or redirecting. The RADI front-end looks good, but there is room for improvement. So I want to redesign the ux/ui. The current RADI front end is not compatible with the desktop app (e.g., I can't go back to the home page after entering exercises). If you're satisfied with my idea and proposal, then I'm going to start working on this issue.

**Comment by Apoorvgarg-creator** [comment]
@codezerro I would like to go through your design proposal first. So We can understand how the system will look. 

For UI/UX, please feel free to share your design and we can both discuss further.

**Comment by codezerro** [comment]
I'll start working on UI/UX in Figma. It takes time, and I'll share it with you.
